#!/bin/bash
sudo apt-get install curl
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install r-base-core
sudo apt-get install python3-pip
sudo apt-get install python3-tk
sudo pip3 install --upgrade pip3
sudo pip3 install -U serenata-toolbox
sudo pip3 install matplotlib